
-- Insert default KisanShaktiAI tenant
INSERT INTO public.tenants (
  id,
  name,
  slug,
  type,
  owner_name,
  owner_email,
  owner_phone,
  status,
  subscription_plan,
  max_farmers,
  max_dealers,
  max_products,
  max_storage_gb,
  max_api_calls_per_day
) VALUES (
  'default',
  'VisionAi Solutions Pvt Ltd',
  'default',
  'agri_company',
  'Amarsinh Patil',
  'amarsinhp@gmail.com',
  '9860989495',
  'active',
  'enterprise',
  10000,
  500,
  1000,
  100,
  100000
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  owner_name = EXCLUDED.owner_name,
  owner_email = EXCLUDED.owner_email,
  owner_phone = EXCLUDED.owner_phone,
  status = EXCLUDED.status,
  subscription_plan = EXCLUDED.subscription_plan;

-- Insert tenant branding for KisanShaktiAI
INSERT INTO public.tenant_branding (
  tenant_id,
  app_name,
  app_tagline,
  logo_url,
  primary_color,
  secondary_color,
  accent_color,
  background_color,
  text_color,
  font_family
) VALUES (
  'default',
  'KisanShaktiAi',
  'Intelligent Guru for Farmers',
  '/lovable-uploads/180cdfdf-9869-4c78-ace0-fdb76e9273b4.png',
  '#4D7C0F',
  '#65A30D',
  '#F59E0B',
  '#FFFFFF',
  '#111827',
  'Inter'
) ON CONFLICT (tenant_id) DO UPDATE SET
  app_name = EXCLUDED.app_name,
  app_tagline = EXCLUDED.app_tagline,
  logo_url = EXCLUDED.logo_url,
  primary_color = EXCLUDED.primary_color,
  secondary_color = EXCLUDED.secondary_color;

-- Insert tenant features for KisanShaktiAI (all features enabled)
INSERT INTO public.tenant_features (
  tenant_id,
  ai_chat,
  weather_forecast,
  marketplace,
  basic_analytics,
  community_forum,
  satellite_imagery,
  soil_testing,
  drone_monitoring,
  iot_integration,
  ecommerce,
  payment_gateway,
  inventory_management,
  logistics_tracking,
  advanced_analytics,
  predictive_analytics,
  custom_reports,
  api_access,
  webhook_support,
  third_party_integrations,
  white_label_mobile_app
) VALUES (
  'default',
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true
) ON CONFLICT (tenant_id) DO UPDATE SET
  ai_chat = EXCLUDED.ai_chat,
  weather_forecast = EXCLUDED.weather_forecast,
  marketplace = EXCLUDED.marketplace,
  basic_analytics = EXCLUDED.basic_analytics,
  community_forum = EXCLUDED.community_forum,
  satellite_imagery = EXCLUDED.satellite_imagery,
  soil_testing = EXCLUDED.soil_testing,
  drone_monitoring = EXCLUDED.drone_monitoring,
  iot_integration = EXCLUDED.iot_integration,
  ecommerce = EXCLUDED.ecommerce,
  payment_gateway = EXCLUDED.payment_gateway,
  inventory_management = EXCLUDED.inventory_management,
  logistics_tracking = EXCLUDED.logistics_tracking,
  advanced_analytics = EXCLUDED.advanced_analytics,
  predictive_analytics = EXCLUDED.predictive_analytics,
  custom_reports = EXCLUDED.custom_reports,
  api_access = EXCLUDED.api_access,
  webhook_support = EXCLUDED.webhook_support,
  third_party_integrations = EXCLUDED.third_party_integrations,
  white_label_mobile_app = EXCLUDED.white_label_mobile_app;
